baseURL = "https://ndtho8205.github.io/"
title = "Rabbit"
languageCode = "en-us"
theme = "blog-theme"

paginate = 100
disqusShortname = ""
googleAnalytics = ""
enableEmoji = true

[params]
  favicon = "images/favicon.ico"
  logo = "images/logo.svg"

[taxonomies]
  categories = "categories"
  series = "series"
  tags = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    identifier = "reading"
    name = "Reading"
    url = "/reading/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[author]
  name = "Tho Nguyen"
  avatar = "images/avatar.jpg"
  CV = ""

[[author.affiliation]]
    name = "Shibaura Institute of Technology"
    position = "Master's Student"
    contact = "mg18502@shibaura-it.ac.jp"

[[author.social]]
    name = "GitHub"
    icon = "images/github.svg"
    url = "https://github.com/ndtho8205"
[[author.social]]
    name = "LinkedIn"
    icon = "images/linkedin.svg"
    url = "https://www.linkedin.com/in/tho-nguyen-duc-a36a73100/"

[[author.projects]]
  [[author.projects.project]]
    name = ""
    description = ""
    link = ""

[[author.publications]]
  name = "Bidirectional LSTM for Continuously Predicting QoE in HTTP Adaptive Streaming"
  authors = "Tho Nguyen Duc, Chanh Tran Minh, Phan Xuan Tan, Kamioka Eiji"
  dest = "Proceedings of the 2019 2nd International Conference on Information Science and Systems (pp. 156-160). ACM"
  link = ""

[[author.publications]]
  name = "Modeling of cumulative QoE in on-demand video services: Role of memory effect and degree of interest"
  authors = "Tho Nguyen Duc, Chanh Tran Minh, Phan Xuan Tan, Kamioka Eiji"
  dest = "Future Internet, 11(8), 171"
  link = ""
